import { fileURLToPath } from "node:url";
import { mkdirSync } from "node:fs";
import { test, expect } from "@playwright/test";
test("citizen signup, wizard, chat, voice status and support work together", async ({page}) => {
  const artifacts = fileURLToPath(new URL("../../../artifacts/", import.meta.url));
  mkdirSync(artifacts, {recursive:true});
  const errors=[]; page.on("pageerror", e => errors.push(e.message));
  page.on("dialog", dialog => dialog.accept());
  const suffix=String(Date.now()).slice(-7);
  await page.goto("/signup");
  await page.getByLabel("Full name", {exact:true}).fill("Prototype Browser Tester");
  await page.getByLabel("Mobile number", {exact:true}).fill("987"+suffix);
  await page.getByLabel("Email", {exact:true}).fill("browser"+suffix+"@example.com");
  await page.getByLabel("Password", {exact:true}).fill("long-browser-test-password");
  await page.getByRole("button",{name:"Create Account",exact:true}).click();
  await expect(page).toHaveURL("http://127.0.0.1:8000/");
  await page.goto("/find-schemes/personal-info");
  await page.getByLabel("Age",{exact:true}).fill("28");
  await page.getByRole("combobox",{name:"Gender",exact:true}).selectOption("Female");
  await page.getByRole("combobox",{name:"Social Category",exact:true}).selectOption("SC");
  await page.getByRole("combobox",{name:"State",exact:true}).selectOption("Uttar Pradesh");
  await page.getByRole("combobox",{name:"District",exact:true}).selectOption("Lucknow");
  await page.getByRole("combobox",{name:"State",exact:true}).selectOption("Tamil Nadu");
  await expect(page.getByRole("combobox",{name:"District",exact:true})).toHaveValue("");
  await expect(page.getByRole("combobox",{name:"District",exact:true}).locator("option")).not.toContainText(["Lucknow"]);
  await page.getByRole("combobox",{name:"State",exact:true}).selectOption("Uttar Pradesh");
  await page.getByRole("combobox",{name:"District",exact:true}).selectOption("Lucknow");
  await page.getByRole("combobox",{name:"Residence",exact:true}).selectOption("Rural");
  await page.getByRole("button",{name:/Continue/}).click();
  await expect(page).toHaveURL(/business-details/);
  await page.locator('[name="businessType"]').selectOption("Service");
  await page.locator('[name="businessActivity"]').fill("Tailoring");
  await page.locator('[name="businessStage"]').selectOption("Startup");
  await page.locator('[name="yearsInBusiness"]').selectOption({index:1});
  await page.locator('[name="annualTurnover"]').selectOption({index:1});
  await page.locator('[name="numberOfEmployees"]').selectOption({index:1});
  await page.getByRole("button",{name:/Continue/}).click();
  await expect(page).toHaveURL(/other-details/);
  for (const name of ["annualIncome","registeredBusiness","fundingRequired","preferredSupport","previousScheme","interestedSchemeType"]) await page.locator('[name="'+name+'"]').selectOption({index:1});
  await page.getByRole("button",{name:/Continue/}).click();
  await expect(page).toHaveURL(/review/);
  await page.getByRole("button",{name:/Find.*Schemes/i}).click();
  await expect(page.locator("article").first()).toBeVisible();
  await expect(page.getByText("Preliminary screening only.",{exact:false}).first()).toBeVisible();
  await page.screenshot({path:artifacts+"/results-desktop.png",fullPage:false});
  await page.goto("/ai-assistant");
  await page.getByRole("textbox").fill("tailoring loan");
  await page.getByRole("textbox").press("Enter");
  await expect(page.getByText("These are catalogue search results", {exact:false})).toBeVisible({timeout:30000});
  await page.goto("/voice-assistant");
  await expect(page.getByText("Bhashini: not configured", {exact:false})).toBeVisible();
  await page.goto("/support");
  await page.getByLabel("Subject",{exact:true}).fill("Browser test support");
  await page.getByLabel("Describe the issue",{exact:true}).fill("Please explain the application document requirements.");
  await page.getByRole("button",{name:"Submit ticket",exact:true}).click();
  await expect(page.getByText("Browser test support",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Opt out",exact:true}).click();
  await expect(page.getByText("You opted out of future SMS outreach.",{exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({path:artifacts+"/support-mobile.png",fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});

